### ISSUE TITLE
Going to scan mode and then back to invoice or hitting home button crashes the app

### ISSUE THREAD

**Issue by bluenem** [NewEconomyMovement/NEMAndroidApp#105]
When I am in scan mode and hit home button or swipe to the left (to get to invoices) the app crashes

**Comment by bluenem** [comment]
that was five minutes ago if that helps

**Comment by fyahfox** [comment]
crashing when going from scan to invoice: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/107

**Comment by am4n0w4r** [comment]
Please test in 0.1.32;

**Comment by bluenem** [comment]
Update 0.1.32:
Going from scan to invoice does not cause a crash but it takes about five seconds and the app gets very sluggish. Buttons are not responding any more.

**Comment by fyahfox** [comment]
Ok, crash is fixed, but that is still not good.
I also experience bad performance when I switch between the 3 tabs in QR view.
Scan is understandable, because it has to initialize the phones camera. But between "My Info" and "Invoice" there shouldnt be much to do. Please take a look if something unneeded is done here or what causes the bad performance.

**Comment by am4n0w4r** [comment]
Please test in 0.1.34, reworked the tab views;

**Comment by fyahfox** [comment]
Performance is fine for switching tabs -> https://github.com/NewEconomyMovement/NEMAndroidApp/issues/112#issuecomment-181811926
