### ISSUE TITLE
Sorting of accounts in account list

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#135]
0.1.34

I think right now the account that was added most recently is on the bottom of the account list. That is fine, but as agreed on the app report, users should be able to manually reorder the account list.

Inside "edit" mode you could just put the pencil icon right next to the account name, and on the left a default reorder icon (these 3 lines) which can be grabbed to reorder the account.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.39; Please make sure you have backup of accounts, as it potentially may interfere with postponed account deletion.

**Comment by fyahfox** [comment]
0.1.39

It doesn't work for me. I can grap the sort icon, drag the account, when I let go, it goes back to the original position.

**Comment by am4n0w4r** [comment]
Hmm, this works on all phones I've tried... Does it show any errors? Please try to move accounts up and down, when there is more than two or three. There was a small issue when moving account down, it was placed always on top of account being dropped onto, not instead of it, so this might be the case. Fixed this in next build.

**Comment by fyahfox** [comment]
No errors, it just didn't work.
But I think I found the problem: When I grab an account and start moving it (direction doesn't matter), I usually also slide to the side of the screen so I can better see where I place it. If you do it like that (very left or very right side) and drop the account it goes back to the original position.

Another thing is: Usually items are reordered directly (while moving/grabbed). Can you do it like that?

**Comment by am4n0w4r** [comment]
Removed side movement effect impact on the list, in 1.0.41; The issue with direct reordering is that Android doesn't have standard reordering list control, so everything should be implemented manually. And with current implementation adding this effect can be tricky and time-consuming, because this is complex list and it will make the drag-n-drop workflow even more complex.

**Comment by fyahfox** [comment]
Ok, thanks for the explanation.
The issue I described is solved in 1.0.41, thanks!
