### ISSUE TITLE
Export account was supposed to be in multiple parts. https://goo.gl/LbR3NW

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#14]

**Comment by fyahfox** [comment]
What he means is that the priv key of an account should not be exported in one piece, but e.g. three, to make it harder for an attacker to get the whole priv key.

Scenario:
An attacker has access to your telegram (messenger) account.
When you now send a priv key from the phone to yourself via telegram (because you also have telegram on your desktop computer and want to import it in your NEM wallet desktop version) the attacker has your priv key.
But if you send one piece via telegram and one piece via another channel, the attacker would need to have access to more communication channels.

The downside is: This makes things complicated, so I suggest to do this:
Let the user export a QR code, but display a warning which says that it is not recommended to send that QR code via an unencrypted communication channel anywhere. If he wants to do it, use at own risk. It is recommended to send the priv key splitted and then send the parts via different channels. If you want to do that tap HERE.

Or something like this.

**Comment by am4n0w4r** [comment]
What if make export still in one piece but encrypted(password-protected)? I mean, user should enter password before exporting and after importing account. Also it is better if password not match wallet password (We can suggest or even enforce this in password requesting popup for example).
   Technically we can take this password, derive encryption key and use it to encrypt only private key part or whole QR. Therefore account export won't relay on secure or multiple channels, and also private key won't be exposed for easy attack. The downsides are: 1)another password, 2) password should be sent via different information channel anyway, or just remembered and not sent at all. And 3) Processing power to decrypt-encrypt data(private key) if private key would be stored encrypted. But I think exporting account is not frequently performed operation so this shouldn't be a real problem.
Technically we can encrypt QR using wallet password but I guess this is not desirable in situations when user wants to transfer account to someone else without access to that remote device and without sharing their wallet password.
This is another suggestion from me.

**Comment by fyahfox** [comment]
Very good thoughts. In my opinion it is good enough though to use the wallet password (at least as a default method - we could also include a checkbox "Use wallet password" which is checked by default and if you uncheck, you can enter a different pw).
Reason: I don't see a use case for transfering an account from person to person. Usually you export an account to a) import an account to another of your devices or b) to have a backup. Transfering accounts to different persons doesnt make sense, becaue the original owner does not lose control over the account.

**Comment by am4n0w4r** [comment]
Completely agree with this. When I said about person to person transferring, I was thinking about like some people working together and using same account for their operations without need to use multisig. This was just a potential thought, and I agree that using wallet password by default with the choice to change it left to user covers this completely.

**Comment by jabo38** [comment]
+1 good solution to the export problem of exporting with QR

**Comment by am4n0w4r** [comment]
Implemented.

**Comment by fyahfox** [comment]
Nice!

Although I would like to suggest some small changes (I can only speak for Android at the moment):

a) The design looks a bit weird. There is a white headline "ENTER EXPORT PASSWORD" on light gray background (bad contrast for readabilty) above the box. I can't exactly tell you how to do it, but usually boxes like this have a headline part (example: http://www.giga.de/androidnews/i/android-app-screenshot.jpg).
b) While the checkbox "Use application password" is checked, there should be no blinking cursor or area where you can type, because that confuses people to still enter something, but that wouldn't make sense.
c) Rephrase the headline from "ENTER EXPORT PASSWORD" to "SET EXPORT PASSWORD" maybe? Then it would also be true for the default case (checkbox checked, nothing entered).
d) I was thinking about a very short explanation what is happening at this step. I guess a lot of people will first think that they have to enter their wallet password so they are allowed to export the account. With that checkbox it will be clear for those who think about it, but to make it more easy I suggest to add a short explanation. Maybe a short text below the box like "Please choose which password should be used to encrypt your exported account."... Maybe somebody can improve the language a bit..?

**Comment by fyahfox** [comment]
"mustfix" applies to a), b) and c)

**Comment by am4n0w4r** [comment]
a, b and c fixed in 0.1.26. Made background darker, so title reads clear now

**Comment by fyahfox** [comment]
see here: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/71
