### ISSUE TITLE
No edit/delete for Address Book

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#143]
0.1.35

I just noticed that for Android it is not possible to edit an address book entry.
Also see here for iOS: https://github.com/NewEconomyMovement/NEMiOSApp/issues/29

**Comment by am4n0w4r** [comment]
Fixed in 0.1.37; All seems to work fine, but I generally recommend to make phone book backup before edit/delete contact testing, just in case;

**Comment by fyahfox** [comment]
Well, there is no way we can make everybody read this warning before testing...
Please make sure the phone contacts are not destroyed. Yes, people should have backups, but we know most dont. And I really dont want anybody to be mad at us because "the NEM app deleted all their contacts"....

**Comment by am4n0w4r** [comment]
We can add warning, for example when user wants to delete contact at the first time. Also, personally, I'd remove possibility to delete not nem contacts. The logic is different because we need to be sure that contacts deletion itself is working good first, so every contact has confirmation in order to split testing steps more clear.
Improved contacts handling in 0.1.39;

**Comment by fyahfox** [comment]
Yes, please remove possibility to delete non-NEM contacts.

Do I understand you correctly? Asking for confirmation is just for testing, it will later be the same logic as for account deleting (undo)?

**Comment by fyahfox** [comment]
0.1.39
Deleting of contacts now works for me.

**Comment by am4n0w4r** [comment]
> Do I understand you correctly? Asking for confirmation is just for testing, it will later be the same logic as for account deleting (undo)?

Yes, seems like all work good, implemented in next build.

**Comment by fyahfox** [comment]
0.1.40
looks good, thx
