### ISSUE TITLE
QR scan behaviour

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/NEMAndroidApp#15]
QR Scans name to address book but it is not found in address book after that. What happen to that address? Where do I find it?

**Comment by fyahfox** [comment]
I don't understand what you mean.

**Comment by am4n0w4r** [comment]
Currently it is stored in device's phonebook as phone contact with custom NEM IM field. Also when sending transaction, this address can be chosen as recipient from the address book.

**Comment by fyahfox** [comment]
Are we talking about the Android version? I can't find an address book view for the current version at all...

**Comment by am4n0w4r** [comment]
Yes about Android version, I attached screenshot with address book button highlighted:
![screenshot-address-book](https://cloud.githubusercontent.com/assets/7976963/10449896/37139636-719f-11e5-9d80-099dd5e77815.png)

**Comment by fyahfox** [comment]
Ah ok, thanks. Well, I guess that will be better after the GUI update :)

**Comment by fyahfox** [comment]
v0.1.24.b1495

When a contact (address) QR is scanned, Android displays a list of all existing contacts on your phone. The user is supposed to pick one contact where the scanned address should be added to.
1) I think the default method should be "Create new contact" but you can also chose to add it to an existing contact. Pretty much the same behaviour when saving a phone number... People are used to that way I think.
2) The custom field where the NEM address will be added is "Chat". Now, I am aware that Android didn't implement a field "NEM address" (yet^^), but isn't this weird? Is there any better solution? Chat is really not nice. And what happens if people already used that custom field "Chat" for a contact?
