### ISSUE TITLE
Cost for sending not there

### ISSUE THREAD

**Issue by rmtodd618** [NewEconomyMovement/NEMAndroidApp#161]
When you send XEM or a message to someone it does not include the fee. I think that should be listed on there for a total.

![screenshot_2016-02-12-20-33-18](https://cloud.githubusercontent.com/assets/8193467/13025242/3958c7c0-d1c8-11e5-8ceb-1022d929b31c.png)

version 0.1.36.b2565

**Comment by rmtodd618** [comment]
The real total was 117. The message I sent before said 0 which had a fee of 10.

**Comment by rmtodd618** [comment]
version 0.1.36.b2565
LG G3
android 5.0.1
kernel version 3.4.0

**Comment by jabo38** [comment]
In message view you can swipe to see how much the fee costs.  That is after the fact.  If a person wants to see for sure what the cost of a transaction is prior to sending, they will have to use the New Transaction feature.  

![image](https://cloud.githubusercontent.com/assets/10395907/13033538/a068dafe-d35d-11e5-8859-b26f3b729b03.png)

**Comment by rmtodd618** [comment]
@jabo38 This does not show on my device like yours does. here is the screen shot in message tab.
![screenshot_2016-02-14-07-47-25](https://cloud.githubusercontent.com/assets/8193467/13034027/61de5020-d2ef-11e5-94bb-7868b8697b7a.png)

**Comment by jabo38** [comment]
Did you try to swipe the transaction to the left? This is not so intuitive for Android people but it is something that iOS people know as iMessages uses that motion.

**Comment by rmtodd618** [comment]
Yes that does work. Thanks.

**Comment by fyahfox** [comment]
Besides that this is an example of extremly bad UX (not blaming anybody, just saying...), this doesn't work good for every TX. First I thought a longer message text is the problem - if that is the case you have to grab the TX at the very top. But then I noticed that I have to grab some 1 line messages on the very top as well, otherwise the slide won't work. But thats another issue, see here: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/170
