### ISSUE TITLE
multisig management

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#176]
1.0.40

We need the possibility to add NEM addresses and labels (from address book) as cosignatory. Please do not drop the feature to use pub keys, but rename the textbox to "Enter address or label". Advanced users will use pub keys, and they will know what to do.

Oh and of course please also implement auto suggestions for addresses and labels.

**Comment by am4n0w4r** [comment]
Currently implemented autocomplete for addresses, public keys and account names, stored in application. It is not possible to add autocomplete from addressbook with current app implementations, because contacts doesn't have public keys stored, and this will lead to unwanted behavior with uninitialized accounts that NIS doesn't know about (accounts which have null public key)
Adding this feature requires changes to existing functionality, like contact storing, handling, and user info QR code structure, both in iOS and Android versions.

**Comment by fyahfox** [comment]
I am not if I understand correctly. Autocomplete for public keys is not needed.

**Comment by am4n0w4r** [comment]
Imagine you have two people - Alice and Bob. Bob have just created his account and has no outgoing transactions, so NIS reports his public key as unknown. Now Alice creates account and wants to add Bob as cosigner. She scans Bob's user info and adds it to address book. Then she uses autocomplete for Bob to add him as cosigner. And here lies the problem - we can display Bob in suggestions but there is no way to find out what his public key is, without passing it along with the address in the QR code.
Also these changes, if implemented, will influence manual contact adding. We'll need to request public key from user, or else contact will be ignored in suggestions.

**Comment by fyahfox** [comment]
Well, in case a pub key for an account is unknown, the app should just inform about it (pub key unknown, account didn't send any transaction yet) and refuse to add this account as cosignatory...

**Comment by kmiliak** [comment]
For this implementation our developers both need 16 hours (8 -IOS and 8 - Android).
They need to add address book contacts to suggestions, and change cosig adding workflow so the app should check on server if added accounts have public keys or not. Than for accounts that have empty public keys we need to show validation messages.

**Comment by fyahfox** [comment]
1.0.42

I just tested it, and I experienced this:
I have account a, b and c. Account a sent a TX before, so its pub key is known to the network. Accounts b and c didnt send a TX yet (pub key unknown).

If I try to set up "a" as multisig:
min cosignatory: 2
cosigner 1: b
cosigner 2: c

I get: "Sending failed! The signature could not be validated"

But it should display, that the cosignatories could not be added because their pub key is unknown.

**Comment by am4n0w4r** [comment]
Well, the problem is not with public keys. Even if accounts b and c didn't send transactions before, they are locally created accounts with public keys known to app, that is enough to add them as cosigners. The problem is that server rejects some aggregate modification transactions while accepting others smoothly. We sent transaction details to you, please take a look because I couldn't find a difference between passing and non-passing transactions.

**Comment by am4n0w4r** [comment]
Fixed in 1.0.43, thanks to @BloodyRookie;

**Comment by fyahfox** [comment]
Ok, the transaction now went through. But after clicking "ok" at "Transaction sent!" popup the app displayed the dashboard for a totally different account. That's a bit confusing, so can you make it so the app goes back to the dashboard of the account, which the user just converted to multisig?

**Comment by fyahfox** [comment]
No idea if that was fixed, but I just checked again and it didn't happen again, so I'll close this issue.
