### ISSUE TITLE
Export Account: Request wallet password

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#28]
0.1.20.b506
Android 4.2.2

When I export an account, it displays the QR code with the priv key without asking me for a password. This proofs that the password is kept in memory even though I never told the app to do so. This is a security issue.

The password should only be kept in memory if the user tells the app explicitely to remember the password.

**Comment by patmast3r** [comment]
or even worse the priv-key is kept in memory.

**Comment by am4n0w4r** [comment]
Actually none of these assumptions are right. Currently in Android version account's private key gets encrypted with AES right after input/creation and never stays unencrypted in the app. It can only be decrypted using account password. That's why transactions ask for password, they need private key to sign themselves. Right after that, the key and password are immediately forgotten.
 When exporting account, it is not necessary to ask for password because private key is transferred still encrypted, so it has no use to any potential attacker but user still can decrypt it when transferred to another device using the account password.

**Comment by fyahfox** [comment]
I see! Thanks for the explanation.

Well, in that case https://github.com/NewEconomyMovement/NEMAndroidApp/issues/14 is not needed anymore imo.

**Comment by am4n0w4r** [comment]
You welcome.
However we will face some issues with this approach when "Enter password once when app is opening" approach is used. And I want to address these in the best possible way.
I know at least two places when we need private key: sending transactions and reading/writing encrypted messages. 
So if user won't have to enter password for these actions, it means that we should just store private key unencrypted, or keeping it still encrypted but store some decrypting info while the app is open. I suggest the following combination:
   We are storing private key encrypted most of the time. When user opens the app, they enter password. From that password an encryption key is generated and stored in memory until app gets paused. This way no password nor private keys are stored in memory. Only decryption key only in memory only for the time app is open. And it is used by app to decrypt-and-forget private key when needed. This approach shouldn't take much processing power and should help at least in the case when device is lost/stolen and potential attacker has access database itself. The weakness is the app is completely vulnerable while visible but this is a usability/security tradeoff.
   Of course we can just store plain unencrypted key and not do all this but it exposes user to the potential risk that if the device is lost, there is big possibility all accounts would get compromised. What do you think? Maybe you'll have better suggestions on this.
Also considering this, I have comments regarding #14, I'll write them there.

**Comment by fyahfox** [comment]
I think that is a very good idea.
I am wondering about some details though. For example: What happens if the NEM app is killed (process killed for whatever reasons)? What happens if the user doesnt close the app correctly (by using the back button) but just hits "home" or switches directly to another app (on android often possible with long press "menu")?

There must be some way to make sure the app forgets the random password-decrypt-key. Maybe with a timer? And the timer only gets reset while the app isused? I think KeePass2Android has similar aproaches, maybe you can look into that.

**Comment by am4n0w4r** [comment]
That's a good question. On Android, if the app process is killed somehow, all objects including static variables are destroyed by runtime. So there shouldn't be any harm if that key wouldn't be stored using specific state saving mechanisms (and it wouldn't because it'd be destroyed by runtime in this case). The other case when user leaves one activity (app screen) normally and switches to another. This can be a little tricky. Timer looks good in the first place but something tells me there can be drawbacks. Maybe I'm wrong, I need to think more on this. I'll also look into KeePass2Android when I have time, maybe I'll discover something there, thanks!

**Comment by fyahfox** [comment]
Ok, thank you!

**Comment by am4n0w4r** [comment]
Can this be closed?

**Comment by fyahfox** [comment]
Well, how did you finally do it? We were discussing the case when a user leaves the app via app screen / long press menu (depends on the device, but thats how it works on my phone) and you wanted to look into how KeePass2Android does it e.g.

**Comment by am4n0w4r** [comment]
When the user leaves app, the encryption key is deleted, so the next time they need to enter password to log back in. No screen can be opened without logging in, except Login and splash.

**Comment by fyahfox** [comment]
and is the key also deleted when the app is not closed regularely but via home button or via app screen?

**Comment by am4n0w4r** [comment]
It doesn't matter how user closes the app - in Android there is no such thing as "Close app", by design (Close buttons you can see in other apps are implemented using tricks, OS doesn't support this).
Yes, whenever user switches to something else - call, lock screen, another app, home screen, etc - the key is being deleted. There is one exception - crash. In this case it's up to Java VM to do the process termination and cleanup.

**Comment by fyahfox** [comment]
ok thank you for this explanation!
