### ISSUE TITLE
Enhancement for low resolution screens

### ISSUE THREAD

**Issue by Xpedite** [NewEconomyMovement/NEMAndroidApp#32]
![capture](https://cloud.githubusercontent.com/assets/15026757/10392247/a4a833ae-6e85-11e5-9fa0-25caee4936af.PNG)
For some pages the menu ( 'messages' , 'scan QR', 'invoice', 'user info')  is displayed while it is not necessary and causes issues for low resolution screens. 
See attached screenshot where the amount text is only partially displayed and it's not possible to swipe to the next field since there is no room. 

this is at screen resolution: 320 x 480 pixels :-) so only applicable to low-end phones.

**Comment by fyahfox** [comment]
Yes, but a GUI overwork is planned anyway. IOS version has it already (I think, cant check because I had to give back my iPhone which I loaned for testing).

It will look like this, which will give us more room:
![qr_create_invoice](https://cloud.githubusercontent.com/assets/6625264/10417409/6ade1dd0-703a-11e5-8f99-da7ba397eda4.png)

**Comment by am4n0w4r** [comment]
I guess this case is no more valid, that screen has been redesigned.

**Comment by fyahfox** [comment]
Yes, although this issue is general and not meant for the screenshot only, I will close it now.

If somebody finds another example of this problem, please comment in here.
