### ISSUE TITLE
No delegated key in Harvest Info

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMAndroidApp#86]
iOS has shown the Delegated Key in Harvest info.  It used to be in My Profile but we deleted that panel, then we decided it would go in Harvest Info.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.30;

**Comment by jabo38** [comment]
fixed

**Comment by fyahfox** [comment]
i think we had a misunderstanding here. it is of no help if the app calculates a random account and displays it as delegated account, because the app is not able to unlock delegated harvesting. this has to be done via NCC/lightwallet.

so until we have that feature (which wont happen too soon) the app should just check the network if delegated harvesting was unlocked (activated) already, and if so, display the delegated address, not priv or pub key.

**Comment by jabo38** [comment]
Also, I have delegated harvesting unlocked on accounts through NCC, but the mobile app is reporting it as locked.  This is because instead of searching through the blockchain for an additional known key, it instead just makes up its own.

**Comment by am4n0w4r** [comment]
I just talked to iOS developer, and he told me that he agreed that only Locked/Unlocked status should be displayed, without any keys or addresses, regardless the status. Is this ok to just hide the key field?

**Comment by fyahfox** [comment]
Yes, just do it like iOS for now. Thanks!

**Comment by am4n0w4r** [comment]
Ok, fixed in 0.1.31;
