### ISSUE TITLE
"Back" button (phone hardware) acts wrongly

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#9]
0.1.20.b506

Sometimes the "back" button doesn't work as expected.
It should not be an "undo" button but more like navigating logicaly through the app, meaning:
Whenever you push the "back" button, the app should go one level up.

Examples:
- Inside message view, back button brings you to account view (works)
- Inside account view, back button leaves app (doesn't always work)
etc.

**Comment by fyahfox** [comment]
Well, the same thing is true for the software "back" button as well of course.

Another bug example:
- Add new account, create new and save, now when you click the "back" button (software or hardware) it brings you back to account creation, but it should leave the app because you were at account overview

**Comment by am4n0w4r** [comment]
I've corrected some of these issues but since we don't have something like site map(or flow chart) defined, there may still be this kind of issues. Please feel free to report if you found any.

**Comment by fyahfox** [comment]
Ok thanks, I will try to test all cases.

**Comment by fyahfox** [comment]
I made this map. I hope I didn't forget anything.

![android app map](https://cloud.githubusercontent.com/assets/6625264/11882218/889adc5e-a50b-11e5-8e98-a4579d1cad19.png)

**Comment by kmiliak** [comment]
Hi,
We had skype conversation on Monday with Makoto, Lon and Jeff, and after that Jeff prepared sitemap and sent it on Trello. I've duplicated it here below:

Map for back arrow
When in Address Book, QR options, or More menu and back is pressed, it goes to the Messages screen.
When in Messages and back is pressed it goes to Account list.
When in Account list there is a configure button instead of back button.
When in Configure the back button leads to the Accounts list.
When is Servers, Map, Harvest Details, or Export Account and back button is pressed, then it goes back to the More menu.
When in New Message, it should go back to messages

**Comment by fyahfox** [comment]
Well, I think it should be like I made it in the app.
Lets discuss that in the skype conference in 45 minutes.

**Comment by am4n0w4r** [comment]
Resolved in 0.1.27

**Comment by fyahfox** [comment]
I think we had one misunderstanding: the hardware back button of the phone should always exit the app when in account list screen...

**Comment by am4n0w4r** [comment]
Fixed in 0.1.27

**Comment by fyahfox** [comment]
ok, thx :)
